### ISSUE TITLE
ModuleNotFoundError: No module named 'faslr'

### ISSUE THREAD

**Issue by son1403** [casact/FASLR#95]
Hi, 

I need help on running FASLR. 
After packages have been installed, I tried to run FASLR by executing the [main.py](https://github.com/casact/FASLR/blob/main/faslr/main.py) file in the [faslr directory](https://github.com/casact/FASLR/tree/main/faslr):
`python -m faslr.main
`
but the output is _"No module named faslr.main"_

Please help me on this step. Thank you so much

**Comment by genedan** [comment]
Thanks for testing this out.

The README is out of date, the `main.py` module has now been renamed to` __main__.py`, so the command to run the program is now:

```
python3 -m faslr
```

Let me know if this works for you. If you'd also like to become a contributor feel free to open up a pull request with the correction and you will be credited with the bug fix in the next release. Otherwise I'll push an update at the end of the week.

**Comment by genedan** [comment]
In addition to the README the other place which has the startup instruction that should be updated is this file:

https://github.com/casact/FASLR/blob/main/docs/user/starting/install.rst

**Comment by son1403** [comment]
> Collaborator

I tried to run this but it can't find module named _'faslr._version'_  because of your changes in setup.py, general.py and init.py yesterday. So i turn it back to the previous version and change numpy version back to 1.20.3 and now it works. 

Thank you so much for your help. 

Son Pham

**Comment by genedan** [comment]
I hadn't committed _version.py yet, but it's there now. Is it working?
